name: demo
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  #set managment
  provider: ^6.0.5
  #cache
  shared_preferences: ^2.2.0
  #language
  easy_localization: ^3.0.0
  #router
  auto_route: ^7.6.0
  #network
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  #model parse 
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  #core eştlik kontrol
  equatable: ^2.0.5
  #network control
  connectivity_plus: ^5.0.2
  url_launcher: ^6.1.12
  package_info_plus: ^5.0.1
  #image
  image_picker: ^1.0.1
  #file
  file_picker: ^6.2.0
  #permission
  permission_handler: ^11.3.0
  app_settings: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator:                    
  build_runner: 
  freezed: ^2.4.1
  very_good_analysis: ^4.0.0+1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/jsons/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
